### PR TITLE
Make chaining of proxies possible by allowing full 32-bit nonce.

### PR DESCRIPTION
**Pull request by flicker581**
I've just added configurable "fullnonce" to config. It allow to use miners non-compatible with nicehash, including proxy chaining. Works for me.

### CODE REVIEW

**Comment by flicker581** [comment]
I think so, but I did not tried it. I use the patch to chain xmrig-proxy.

**Comment by uaktags** [comment]
It doesn't appear so, atleast from my test. Still get the nonce issue on the proxy and it reports 0.0 from the workers even though they are mining.

**Comment by flicker581** [comment]
Thanks, I've added one additional check against this error. Please try it out.

**Comment by uaktags** [comment]
I'm more than happy to test!
So running with the new code, I still get 
```
rejected (0/1+0) diff 200007 "Invalid nonce; is miner not compatible with NiceHash?"
```

and the miners report 
```
|     1 | Invalid nonce; is miner not comp | 2018-01-19 04:16:28 |
```

**Comment by flicker581** [comment]
This is quite strange. Have you set "fullnonce: true" in config.json? What is your setup?

**Comment by uaktags** [comment]
Yep, got it setup with fullnonce as true. I can spin up a different miner other than xmr-stak if need be
```
{
    "background": false,
    "log-file": null,
    "access-log-file": null,
    "retries": 5,
    "retry-pause": 5,
    "donate-level": 0,
    "coin": "xmr",
    "custom-diff": 0,
    "syslog": false,
    "verbose": false,
    "colors": true,
    "workers": true,
    "fullnonce": true,
    "pools": [
        {
            "url": "cryptonight.usa.nicehash.com:3355",
            "user": "bitcoin-address",
            "pass": "x"
        }
    ],
    "bind": [
        "0.0.0.0:3333"
    ],
    "api": {
        "port": 0,
        "access-token": null,
        "worker-id": null
    }
}
```

in XMR-Stak
```
"pool_list" :
[
        {"pool_address" : "10.0.0.2:3333", "wallet_address" : "cloud", "pool_password" : "x", "use_nicehash" : true, "use_tls" : false, "tls_fingerprint" : "", "pool_weight" : 1 },
],
```

**Comment by uaktags** [comment]
nope, can confirm that with xmrig 2.4, it still shows 
[2018-01-20 03:21:54] rejected (0/1) diff 200007 "Invalid nonce; is miner not compatible with NiceHash?" (9

**Comment by flicker581** [comment]
Difficulty of 200000 is too much for my testing server, but I've just managed to submit 2 shares using your config with little modifications. It is accepted:

WORKER NAME             | LAST IP         | COUNT | ACCEPTED | REJ |     10 MIN |
test1                   | 127.0.0.1       |     2 |        2 |   0 |   0.3 kH/s |

So, please double-check if you applied the patches correctly. I am using the same xmr-stak.

**Comment by uaktags** [comment]
You're absolutely right, must have missed something during my checkouts and not properly checking out your PR. 
```
[2018-01-20 20:08:46] #000 accepted (2/0+0) diff 200007 (122 ms)
[2018-01-20 20:08:50] 6.7 kH/s, shares: 2/0 +2, upstreams: 2, miners: 2 (max 2) +0/-0
WORKER NAME             | LAST IP         | COUNT | ACCEPTED | REJ |     10 MIN |
cloud2                  | 10.250.0.8      |     1 |        1 |   0 |   0.3 kH/s |
cloud                   | 10.250.0.7      |     1 |        1 |   0 |   0.3 kH/s |
```
So can confirm....user error :-P
👍

**Comment by ddebin** [comment]
👍 PR works for me too with NiceHash! But you get as many upstream connections (to NiceHash) as workers and it looks like _custom-diff_ doesn't work.

**Comment by uaktags** [comment]
I think the issue with that is more by design of xmrig-proxy, rather than
this PR. (Disclaimer, I could be totally wrong). A few comparison areas
shows that xmrig-proxy do what Snipa's node-proxy does where the proxy
splits the work down between the workers before submitting it off to the
pool. See https://github.com/xmrig/xmrig-proxy/wiki/Comparison.
So it doesn't really reduce the load (workers hitting nicehash) and doesn't
reduce the difficulty for the workers. So each worker still needs to be
able to do 200007 diff.

**Comment by flicker581** [comment]
Obviously each connection to a worker needs to be mapped to an individual connection to Nicehash. This is by design.

Custom difficulty must work, nevertheless. It is intended to exist only between proxy and worker.

**Comment by ddebin** [comment]
What's the purpose of this change ? https://github.com/xmrig/xmrig-proxy/pull/83/files#diff-11c2fdd840c3c84c8c9fdbe3f8f768e3R174

Without it, it still works and it removes the 1:1 mapping between miners and nicehash. With a custom-diff (which seems to work indeed), a large number of upstream connections were left without activity and were therefore alternately closed by Nicehash and reopened by the proxy.

**Comment by flicker581** [comment]
This change is needed because there can be only one 1:256 mapping in the chain. This mapping needs to put worker id in one of 4 bytes of the nonce. When working with nicehash, this is done by nicehash already. 

If your workers are too slow for nicehash, you are out of business.

The concept may be extended further to allow arbitrary nonce size (to make slow worker pooling working again), but this needs corresponding changes at worker's side.

**Comment by alebeta90** [comment]
@flicker581 just for your information, the solution you provided works just fine with webminer. 

Thanks

**Comment by oldschoola41** [comment]
So in order to make xmr-node-proxy work with nicehash we can only use heavy duty miners? any specific hash rate ?

**Comment by oldschoola41** [comment]
also do we need to download a new version of the xmr proxy node ?

**Pull request closed without merging**
